### ISSUE TITLE
Release Creation issue in Octopus Deploy

### ISSUE THREAD

**Issue by ozinus** [xebialabs-community/xlr-octopus-deploy-plugin#2]
Hi,
Thanks for your effort.

I have tried to use the plug in but getting this error. I am attaching the log file which XL release generates.
[script_output_20180816095517.log](https://github.com/xebialabs-community/xlr-octopus-deploy-plugin/files/2297273/script_output_20180816095517.log)

Also , the plug in I am using to create a release requires more parameters than the screenshot/source code at the git. I am attaching those screen shots too.

![create_release_deployed](https://user-images.githubusercontent.com/7674398/44267632-05266400-a1fd-11e8-9887-11336ed5e593.jpg)
+

![created_release_on_git](https://user-images.githubusercontent.com/7674398/44267665-1f604200-a1fd-11e8-86d3-60365639e135.png)

Look forward to your thoughts.

**Comment by vlussenburg** [comment]
Hi @ozinus, I'll look at this ASAP but that'll probably not be till next  week!

**Comment by vlussenburg** [comment]
@ozinus "Also , the plug in I am using to create a release requires more parameters than the screenshot/source code at the git. I am attaching those screen shots too."

Could you provide this code? Using a fork or a pull request?

**Comment by ozinus** [comment]
Hi,
Is this issue fixed.

**Comment by vlussenburg** [comment]
Nope

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vlussenburg** [comment]
@ozinus I'm not sure I understand where your extra fields come from. Have you customized the plugin?

**Comment by ozinus** [comment]
@vlussenburg I have not done any customization. Xebia labs plugin looks like the top image from my post. So you are saying that this plugin never looked like that on the Git...?

**Comment by vlussenburg** [comment]
@ozinus that's right. Where did you get the JAR file from?

**Comment by vlussenburg** [comment]
@zvercodebender any ideas here?

**Comment by vlussenburg** [comment]
@ozinus I'm going to close this issue if I can't verify the plugin! Let me know!

**Comment by vlussenburg** [comment]
Customizations are the culprit - closing issue
